/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jug_gvsmirnov_javaagent_jvmti_JvmtiAgent */

#ifndef _Included_jug_gvsmirnov_javaagent_jvmti_JvmtiAgent
#define _Included_jug_gvsmirnov_javaagent_jvmti_JvmtiAgent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jug_gvsmirnov_javaagent_jvmti_JvmtiAgent
 * Method:    startNativeAgent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jug_gvsmirnov_javaagent_jvmti_JvmtiAgent_startNativeAgent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
